-------------------------------------------------------------------------------
--Script to query database level setting information.
-------------------------------------------------------------------------------
	
	SELECT d.name AS Database,
	ISNULL(dp.name, 'Not Found') AS Owner,
	d.compatibility_level AS CompatabilityLevel,
	d.collation_name AS Collation,
	d.user_access_desc AS UserAccess,
	d.is_read_only AS ReadOnly,
	d.is_auto_close_on AS AutoClose,
	d.is_auto_shrink_on AS AutoShrink,
	d.state_desc AS State,
	d.is_in_standby AS Standby,
	--d.is_cleanly_shutdown AS CleanlyShutDown,
	--d.is_supplemental_logging_enabled AS IsSuppLoggingEnabled,
	d.snapshot_isolation_state_desc AS SnapshotIsolation,
	d.is_read_committed_snapshot_on AS ReadCommittedSnapshot,
	d.recovery_model_desc AS RecoveryModel,
	d.page_verify_option_desc AS PageVerifyOption,
	d.is_auto_create_stats_on AS AutoCreateStats,
	d.is_auto_update_stats_on AS AutoUpdateStats,
	d.is_auto_update_stats_async_on AS AutoUpdateAsync,
	d.is_ansi_null_default_on AS AnsiNullDefault,
	d.is_ansi_nulls_on AS AnsiNull,
	d.is_ansi_padding_on AS AnsiPadding,
	d.is_ansi_warnings_on AS AnsiWarning,
	d.is_arithabort_on AS ArithAbort,
	d.is_concat_null_yields_null_on AS ConcatNullYieldsNull,
	d.is_numeric_roundabort_on AS NumericRoundAbort,
	d.is_quoted_identifier_on AS QuotedIdentifier,
	d.is_recursive_triggers_on AS RecursiveTriggers,
	d.is_cursor_close_on_commit_on AS CursorCloseCommit,
	d.is_local_cursor_default AS LocalCursorDefault,
	d.is_fulltext_enabled AS FullTextEnabled,
	d.is_trustworthy_on AS Trustworthy,
	d.is_db_chaining_on As DbChaining,
	d.is_parameterization_forced AS ParameterizeForced,
	d.is_master_key_encrypted_by_server AS MasterKeyEncryptServer,
	--d.is_published AS Published,
	--d.is_subscribed AS Subscribed,
	--d.is_merge_published AS MergePublished,
	--d.is_distributor AS Distributor,
	--d.is_sync_with_backup AS SyncWithBackup,
	d.is_broker_enabled AS BrokerEnabled,
	--d.log_reuse_wait_desc AS LogReuseWait,
	--d.is_date_correlation_on AS DateCorrelate,
	--d.is_cdc_enabled AS CdcEnabled,
	ISNULL(d.is_encrypted, 0) AS Encrypted,
	ISNULL(dek.encryption_state, 0) AS EncryptState,
	ISNULL(dek.create_date, '9999-12-31') AS EncryptCreate,
	ISNULL(dek.modify_date, '9999-12-31') AS EncryptModify,
	ISNULL(dek.key_algorithm, '') AS KeyAlgorithm,
	ISNULL(dek.key_length, 0) AS KeyLength,
	ISNULL(CONVERT(VARCHAR(1000), dek.encryptor_thumbprint, 1), '') AS EncryptThumbprint,
	ISNULL(dek.encryptor_type, '') AS EncryptType
FROM sys.databases d
LEFT OUTER JOIN sys.database_principals dp ON d.owner_sid = dp.sid
LEFT OUTER JOIN sys.dm_database_encryption_keys dek ON d.database_id = dek.database_id